// frontend/src/app/features/emergency/emergency.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { BloodRequestService } from '../../core/services/blood-request.service';
import { ToastService } from '../../core/services/toast.service';
import { CustomValidators } from '../../core/validators/custom.validators';
import { BloodRequest } from '../../core/models/models';

@Component({
  selector: 'app-emergency',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterModule],
  template: `
    <div class="max-w-3xl mx-auto py-12 px-4 sm:px-6">
      <!-- Emergency Header Alert -->
      <div class="p-4 rounded-2xl bg-gradient-to-r from-red-600 to-rose-600 text-white flex items-center justify-between shadow-lg shadow-red-600/30 mb-8">
        <div class="flex items-center gap-3">
          <span class="text-2xl animate-pulse">🚨</span>
          <div>
            <h1 class="font-bold text-base sm:text-lg">Emergency Blood Broadcast System</h1>
            <p class="text-xs text-red-100">Automatically broadcasts requests to compatible nearby donors in seconds</p>
          </div>
        </div>
        <div class="hidden sm:block text-right text-xs">
          <span class="font-bold block">Avg Response</span>
          <span class="text-red-200">4.2 Minutes</span>
        </div>
      </div>

      <div class="p-8 sm:p-10 rounded-3xl bg-white dark:bg-dark-card border border-gray-200 dark:border-gray-800 shadow-glass dark:shadow-glass-dark space-y-6">
        <div class="border-b border-gray-100 dark:border-gray-800 pb-4">
          <h2 class="text-xl font-bold text-gray-900 dark:text-white font-display">Blood Requisition Details</h2>
          <p class="text-xs text-gray-500 dark:text-gray-400 mt-1">Please provide accurate hospital and patient details</p>
        </div>

        <form [formGroup]="emergencyForm" (ngSubmit)="onSubmit()" class="space-y-6">
          <div *ngIf="errorMessage" class="p-3 rounded-xl bg-red-50 dark:bg-red-950/40 border border-red-200 dark:border-red-900 text-xs text-red-600 font-medium">
            {{ errorMessage }}
          </div>

          <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <!-- Patient Name -->
            <div class="space-y-1">
              <label class="text-xs font-semibold text-gray-700 dark:text-gray-300">Patient Full Name *</label>
              <input type="text" formControlName="patientName" placeholder="Patient Name"
                     class="w-full px-3.5 py-2.5 rounded-xl text-sm border bg-gray-50/50 dark:bg-gray-800/50 border-gray-300 dark:border-gray-700 text-gray-900 dark:text-white"
                     [ngClass]="{'border-red-500': f['patientName'].touched && f['patientName'].invalid}">
              <p *ngIf="f['patientName'].touched && f['patientName'].invalid" class="text-[11px] text-red-500">Patient name is required</p>
            </div>

            <!-- Blood Group Needed -->
            <div class="space-y-1">
              <label class="text-xs font-semibold text-gray-700 dark:text-gray-300">Blood Group Required *</label>
              <select formControlName="bloodGroup"
                      class="w-full px-3.5 py-2.5 rounded-xl text-sm border bg-gray-50/50 dark:bg-gray-800/50 border-gray-300 dark:border-gray-700 text-gray-900 dark:text-white">
                <option value="A_POSITIVE">A+ (A Positive)</option>
                <option value="A_NEGATIVE">A- (A Negative)</option>
                <option value="B_POSITIVE">B+ (B Positive)</option>
                <option value="B_NEGATIVE">B- (B Negative)</option>
                <option value="AB_POSITIVE">AB+ (AB Positive)</option>
                <option value="AB_NEGATIVE">AB- (AB Negative)</option>
                <option value="O_POSITIVE">O+ (O Positive)</option>
                <option value="O_NEGATIVE">O- (O Negative)</option>
              </select>
            </div>

            <!-- Units Needed -->
            <div class="space-y-1">
              <label class="text-xs font-semibold text-gray-700 dark:text-gray-300">Units Required (1 - 20) *</label>
              <input type="number" formControlName="unitsNeeded" min="1" max="20"
                     class="w-full px-3.5 py-2.5 rounded-xl text-sm border bg-gray-50/50 dark:bg-gray-800/50 border-gray-300 dark:border-gray-700 text-gray-900 dark:text-white">
            </div>

            <!-- Urgency Level -->
            <div class="space-y-1">
              <label class="text-xs font-semibold text-gray-700 dark:text-gray-300">Priority Level *</label>
              <select formControlName="urgencyLevel"
                      class="w-full px-3.5 py-2.5 rounded-xl text-sm border bg-gray-50/50 dark:bg-gray-800/50 border-gray-300 dark:border-gray-700 text-gray-900 dark:text-white">
                <option value="CRITICAL">🚨 CRITICAL (Immediate / Under 4 hours)</option>
                <option value="URGENT">⚡ URGENT (Surgery scheduled / Within 24h)</option>
                <option value="NORMAL">🟢 NORMAL (Within 48 hours)</option>
              </select>
            </div>

            <!-- Hospital Name -->
            <div class="space-y-1">
              <label class="text-xs font-semibold text-gray-700 dark:text-gray-300">Hospital / Facility Name *</label>
              <input type="text" formControlName="hospitalName" placeholder="e.g. Apollo Hospital"
                     class="w-full px-3.5 py-2.5 rounded-xl text-sm border bg-gray-50/50 dark:bg-gray-800/50 border-gray-300 dark:border-gray-700 text-gray-900 dark:text-white">
            </div>

            <!-- Required By Date -->
            <div class="space-y-1">
              <label class="text-xs font-semibold text-gray-700 dark:text-gray-300">Required By Date & Time *</label>
              <input type="datetime-local" formControlName="requiredByDate"
                     class="w-full px-3.5 py-2.5 rounded-xl text-sm border bg-gray-50/50 dark:bg-gray-800/50 border-gray-300 dark:border-gray-700 text-gray-900 dark:text-white">
            </div>
          </div>

          <!-- Hospital Address & Location -->
          <div class="space-y-3">
            <div class="space-y-1">
              <label class="text-xs font-semibold text-gray-700 dark:text-gray-300">Hospital Address *</label>
              <input type="text" formControlName="hospitalAddress" placeholder="Full street address of hospital"
                     class="w-full px-3.5 py-2.5 rounded-xl text-sm border bg-gray-50/50 dark:bg-gray-800/50 border-gray-300 dark:border-gray-700 text-gray-900 dark:text-white">
            </div>
            <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div class="space-y-1">
                <label class="text-xs font-semibold text-gray-700 dark:text-gray-300">City *</label>
                <input type="text" formControlName="city" placeholder="e.g. New Delhi / Bangalore"
                       class="w-full px-3.5 py-2.5 rounded-xl text-sm border bg-gray-50/50 dark:bg-gray-800/50 border-gray-300 dark:border-gray-700 text-gray-900 dark:text-white">
              </div>
              <div class="space-y-1">
                <label class="text-xs font-semibold text-gray-700 dark:text-gray-300">Pincode *</label>
                <input type="text" formControlName="pincode" placeholder="6 digits" maxlength="6"
                       class="w-full px-3.5 py-2.5 rounded-xl text-sm border bg-gray-50/50 dark:bg-gray-800/50 border-gray-300 dark:border-gray-700 text-gray-900 dark:text-white">
              </div>
            </div>
          </div>

          <!-- Contact & Reason -->
          <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div class="space-y-1">
              <label class="text-xs font-semibold text-gray-700 dark:text-gray-300">Emergency Contact Number *</label>
              <input type="tel" formControlName="contactNumber" placeholder="98XXXXXXXX" maxlength="10"
                     class="w-full px-3.5 py-2.5 rounded-xl text-sm border bg-gray-50/50 dark:bg-gray-800/50 border-gray-300 dark:border-gray-700 text-gray-900 dark:text-white"
                     [ngClass]="{'border-red-500': f['contactNumber'].touched && f['contactNumber'].invalid}">
              <p *ngIf="f['contactNumber'].touched && f['contactNumber'].invalid" class="text-[11px] text-red-500">10-digit number required</p>
            </div>
            <div class="space-y-1">
              <label class="text-xs font-semibold text-gray-700 dark:text-gray-300">Medical Reason / Surgery Type *</label>
              <input type="text" formControlName="reason" placeholder="e.g. Emergency Cardiac Surgery / Accident"
                     class="w-full px-3.5 py-2.5 rounded-xl text-sm border bg-gray-50/50 dark:bg-gray-800/50 border-gray-300 dark:border-gray-700 text-gray-900 dark:text-white">
            </div>
          </div>

          <div class="space-y-1">
            <label class="text-xs font-semibold text-gray-700 dark:text-gray-300">Additional Instructions (Optional)</label>
            <textarea formControlName="description" rows="2" placeholder="e.g. Please report to 3rd floor Blood Bank, Attendant name: Ramesh"
                      class="w-full px-3.5 py-2 rounded-xl text-sm border bg-gray-50/50 dark:bg-gray-800/50 border-gray-300 dark:border-gray-700 text-gray-900 dark:text-white"></textarea>
          </div>

          <button type="submit" [disabled]="emergencyForm.invalid || isLoading"
                  class="w-full py-4 px-4 rounded-xl bg-gradient-to-r from-red-600 to-rose-600 hover:from-red-700 hover:to-rose-700 disabled:opacity-50 text-white font-extrabold text-base shadow-lg shadow-red-600/30 transition-all flex items-center justify-center gap-2">
            <span *ngIf="isLoading" class="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></span>
            <span>{{ isLoading ? 'Broadcasting to donors...' : 'Broadcast Emergency Blood Request' }}</span>
          </button>
        </form>
      </div>
    </div>
  `
})
export class EmergencyComponent {
  emergencyForm: FormGroup;
  isLoading = false;
  errorMessage = '';

  constructor(
    private fb: FormBuilder,
    private bloodRequestService: BloodRequestService,
    private toastService: ToastService,
    private router: Router
  ) {
    const tomorrow = new Date();
    tomorrow.setDate(tomorrow.getDate() + 1);

    this.emergencyForm = this.fb.group({
      patientName: ['', [Validators.required, Validators.minLength(2)]],
      bloodGroup: ['B_POSITIVE', [Validators.required]],
      unitsNeeded: [2, [Validators.required, Validators.min(1), Validators.max(20)]],
      urgencyLevel: ['CRITICAL', [Validators.required]],
      hospitalName: ['', [Validators.required]],
      hospitalAddress: ['', [Validators.required]],
      city: ['', [Validators.required]],
      pincode: ['', [Validators.required, CustomValidators.pincode()]],
      requiredByDate: [tomorrow.toISOString().slice(0, 16), [Validators.required]],
      contactNumber: ['', [Validators.required, CustomValidators.phone()]],
      reason: ['', [Validators.required]],
      description: ['']
    });
  }

  get f() { return this.emergencyForm.controls; }

  onSubmit(): void {
    if (this.emergencyForm.invalid) return;

    this.isLoading = true;
    this.errorMessage = '';

    this.bloodRequestService.createRequest(this.emergencyForm.value).subscribe({
      next: (res: BloodRequest) => {
        this.isLoading = false;
        this.toastService.success(`Emergency request broadcasted! ${res.donorsNotified} nearby compatible donors notified.`);
        this.router.navigate(['/requests']);
      },
      error: (err: any) => {
        this.isLoading = false;
        this.errorMessage = err.error?.message || 'Failed to submit emergency request. Please try again.';
      }
    });
  }
}

// app/emergency/page.tsx
"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { Badge } from "@/components/ui/badge"
import { AlertTriangle, Phone, Clock, Users, Heart } from "lucide-react"
import { Header } from "@/components/header"

export default function EmergencyPage() {
  const [urgencyLevel, setUrgencyLevel] = useState("")
  const [bloodType, setBloodType] = useState("")

  return (
    <div className="min-h-screen bg-background">
      <Header />

      {/* Emergency Alert Banner */}
      <div className="bg-destructive text-destructive-foreground py-4">
        <div className="container flex items-center justify-center gap-3">
          <AlertTriangle className="h-6 w-6 animate-pulse" />
          <span className="text-lg font-semibold">EMERGENCY BLOOD REQUEST SYSTEM</span>
          <Badge variant="secondary" className="bg-white text-destructive">
            24/7 Active
          </Badge>
        </div>
      </div>

      <div className="container py-12">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-8">
            <h1 className="text-4xl font-bold text-foreground mb-4">Emergency Blood Request</h1>
            <p className="text-lg text-muted-foreground">
              Submit urgent blood requests that will be immediately broadcasted to all compatible donors in your area
            </p>
          </div>

          <div className="grid lg:grid-cols-3 gap-8">
            {/* Emergency Form */}
            <div className="lg:col-span-2">
              <Card className="border-destructive/20">
                <CardHeader>
                  <CardTitle className="text-2xl text-destructive">
                    <AlertTriangle className="h-6 w-6 inline mr-2" />
                    Emergency Request Form
                  </CardTitle>
                  <CardDescription>
                    All fields are required. This request will be sent immediately to nearby donors.
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-6">
                  <div className="grid md:grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <Label htmlFor="bloodType">Blood Type Required *</Label>
                      <Select value={bloodType} onValueChange={setBloodType}>
                        <SelectTrigger>
                          <SelectValue placeholder="Select blood type" />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="A+">A+</SelectItem>
                          <SelectItem value="A-">A-</SelectItem>
                          <SelectItem value="B+">B+</SelectItem>
                          <SelectItem value="B-">B-</SelectItem>
                          <SelectItem value="AB+">AB+</SelectItem>
                          <SelectItem value="AB-">AB-</SelectItem>
                          <SelectItem value="O+">O+</SelectItem>
                          <SelectItem value="O-">O- (Universal)</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor="urgency">Urgency Level *</Label>
                      <Select value={urgencyLevel} onValueChange={setUrgencyLevel}>
                        <SelectTrigger>
                          <SelectValue placeholder="Select urgency" />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="critical">Critical (Life-threatening)</SelectItem>
                          <SelectItem value="urgent">Urgent (Surgery scheduled)</SelectItem>
                          <SelectItem value="high">High (Within 24 hours)</SelectItem>
                          <SelectItem value="moderate">Moderate (Within 48 hours)</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                  </div>

                  <div className="grid md:grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <Label htmlFor="hospital">Hospital/Medical Facility *</Label>
                      <Input id="hospital" placeholder="Enter hospital name" />
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor="units">Units Needed *</Label>
                      <Input id="units" type="number" placeholder="Number of units" min="1" max="10" />
                    </div>
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="location">Exact Location *</Label>
                    <Input id="location" placeholder="Hospital address or coordinates" />
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="contact">Emergency Contact *</Label>
                    <Input id="contact" placeholder="Phone number for immediate contact" />
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="details">Medical Details</Label>
                    <Textarea
                      id="details"
                      placeholder="Additional medical information, patient condition, special requirements..."
                      rows={4}
                    />
                  </div>

                  <div className="flex gap-4">
                    <Button className="flex-1 emergency-gradient hover:opacity-90 text-lg py-6">
                      <AlertTriangle className="h-5 w-5 mr-2" />
                      Submit Emergency Request
                    </Button>
                    <Button variant="outline" className="px-8 bg-transparent">
                      <Phone className="h-4 w-4 mr-2" />
                      Call 911
                    </Button>
                  </div>
                </CardContent>
              </Card>
            </div>

            {/* Emergency Info Sidebar */}
            <div className="space-y-6">
              <Card className="bg-primary/5 border-primary/20">
                <CardHeader>
                  <CardTitle className="text-primary">
                    <Clock className="h-5 w-5 inline mr-2" />
                    Response Time
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="text-3xl font-bold text-primary mb-2">4.2 min</div>
                  <p className="text-sm text-muted-foreground">Average emergency response time</p>
                </CardContent>
              </Card>

              <Card className="bg-accent/5 border-accent/20">
                <CardHeader>
                  <CardTitle className="text-accent">
                    <Users className="h-5 w-5 inline mr-2" />
                    Active Donors
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="text-3xl font-bold text-accent mb-2">1,247</div>
                  <p className="text-sm text-muted-foreground">Available in your area</p>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle>
                    <Heart className="h-5 w-5 inline mr-2" />
                    Emergency Hotline
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="text-2xl font-bold text-destructive mb-2">1-800-BLOOD-911</div>
                  <p className="text-sm text-muted-foreground mb-4">24/7 Emergency Blood Services</p>
                  <Button
                    variant="outline"
                    className="w-full border-destructive text-destructive hover:bg-destructive hover:text-destructive-foreground bg-transparent"
                  >
                    <Phone className="h-4 w-4 mr-2" />
                    Call Now
                  </Button>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle>Blood Type Compatibility</CardTitle>
                </CardHeader>
                <CardContent className="space-y-2">
                  <div className="text-sm">
                    <strong>Universal Donors:</strong> O-
                  </div>
                  <div className="text-sm">
                    <strong>Universal Recipients:</strong> AB+
                  </div>
                  <div className="text-sm text-muted-foreground">
                    Our system automatically finds compatible donors based on medical compatibility rules.
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
